
// import "../styles/main.scss";
// import { Inter } from "next/font/google";
// import { Toaster } from "react-hot-toast";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en"  className="mdl-js">
//       <body className={inter.className} >
//         {children}
//         <Toaster position="top-right" reverseOrder={false} />
//       </body>
//     </html>
//   );
// }


// app/layout.js
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "../styles/main.scss";
import IntlProvider from "./providers/IntlProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inventory Software Management",
  description: "Inventory System",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className="mdl-js">
      <body className={inter.className}>
        <IntlProvider>
          {children}
          <Toaster position="top-right" />
        </IntlProvider>
      </body>
    </html>
  );
}
